version: '3.8'

services:
  website:
    build:
      context: ../../website
      dockerfile: ../../website/Dockerfile
    ports:
      - "3000:80" # host:container
    depends_on:
      - web-api
    networks:
      - supermarket-net

  web-api:
    build:
      context: ../../web-api
      dockerfile: ../../web-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
    networks:
      - supermarket-net

  engine:
    build:
      context: ../../engine
      dockerfile: ../../engine/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENGINE_PORT=8081
    networks:
      - supermarket-net

networks:
  supermarket-net:
    driver: bridge
